// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3244.BrotherhoodOfSteel;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Victor;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController myDriveTrainleftMotor;
    public static SpeedController myDriveTrainrightMotor;
    public static DifferentialDrive myDriveTrainDifferentialDrive1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        myDriveTrainleftMotor = new Victor(0);
        LiveWindow.addActuator("MyDriveTrain", "leftMotor", (Victor) myDriveTrainleftMotor);
        myDriveTrainleftMotor.setInverted(false);
        myDriveTrainrightMotor = new Victor(1);
        LiveWindow.addActuator("MyDriveTrain", "rightMotor", (Victor) myDriveTrainrightMotor);
        myDriveTrainrightMotor.setInverted(false);
        myDriveTrainDifferentialDrive1 = new DifferentialDrive(myDriveTrainleftMotor, myDriveTrainrightMotor);
        LiveWindow.addActuator("MyDriveTrain", "Differential Drive 1", myDriveTrainDifferentialDrive1);
        myDriveTrainDifferentialDrive1.setSafetyEnabled(true);
        myDriveTrainDifferentialDrive1.setExpiration(0.1);
        myDriveTrainDifferentialDrive1.setMaxOutput(1.0);


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
